(function(){var i,n;i=function(){function f(){this.data=[];this.children={}}if(!String.prototype.startsWith)String.prototype.startsWith=function(g){return this.slice(0,g.length)===g};if(!String.prototype.endsWith)String.prototype.endsWith=function(g){return this.slice(-g.length)===g};f.fromJSON=function(g){var a=new f;Array.isArray(g)?a.data=g:Object.keys(g).forEach(function(b){b===""?a.data=g[b]:a.children[b]=f.fromJSON(g[b])});return a};f.prototype.toJSON=function(){var g=Object.keys(this.children),
a;if(g.length===0)return this.data;this.data.length&&g.push("");g.sort();a={};g.forEach(function(b){a[b]=b?this.children[b].toJSON():this.data}.bind(this));return a};f.prototype.findNode=function(g){var a,b;if(!g)return[this,"",""];b=Object.keys(this.children);for(a=0;a<b.length;a++){if(g.startsWith(b[a]))return this.children[b[a]].findNode(g.slice(b[a].length));if(g.charAt(0)===b[a].charAt(0))return[this,g,b[a]]}return[this,g,""]};f.prototype.forEach=function(g,a){var b=Object.keys(this.children),
a=a||"";this.data.length&&g(a,this.data);b.sort();b.forEach(function(b){this.children[b].forEach(g,a+b)}.bind(this))};f.prototype.forEachPrefix=function(g,a){var b=this.findNode(g);!b[1]&&!b[2]?b[0].forEach(a,g):b[2].startsWith(b[1])&&b[0].children[b[2]].forEach(a,g.slice(0,-b[1].length)+b[2])};f.prototype.get=function(g){g=this.findNode(g);return!g[1]&&!g[2]&&g[0].data.length?g[0].data:null};f.prototype.add=function(g,a){var b=this.findNode(g),c,d;if(!b[1]&&!b[2])b[0].data.push(a);else if(b[2]){c=
b[1];d=b[2];for(var e=0;e<c.length&&e<d.length&&c.charAt(e)===d.charAt(e);)e++;c=c.slice(0,e);d=b[0].children[b[2]];delete b[0].children[b[2]];b[0].children[c]=new f;b[0].children[c].children[b[2].slice(c.length)]=d;b[1]===c?b[0].children[c].data.push(a):(b[0].children[c].children[b[1].slice(c.length)]=new f,b[0].children[c].children[b[1].slice(c.length)].data.push(a))}else b[0].children[b[1]]=new f,b[0].children[b[1]].data.push(a)};f.prototype.findFuzzy=function(g,a){var b=[],c=g.length+1,d=c+a,
e=[],h;for(h=0;h<d*c;h++)e[h]=h<c?h:h%c===0?h/c:a+1;this.fuzzyRecurse(g,a,b,e,1,c,"");return b};f.prototype.fuzzyRecurse=function(g,a,b,c,d,e,h){var f=d*e;this.data&&(f=c[f-1],f<=a&&b.push([h,this.data,f]));Object.keys(this.children).forEach(function(f){var o=d,j,l,p,r,q,k,i,m,n,s;for(j=0;j<f.length;j++,o++){l=f.charAt(j);p=e*o;r=p-e;q=c[p];k=Math.max(0,o-a-1);for(i=Math.min(e-1,o+a);k<i;k++)m=c[r+k]+(l!==g.charAt(k)?1:0),n=c[r+k+1]+1,s=c[p+k]+1,m=Math.min(m,n,s),c[p+k+1]=m,m<q&&(q=m);if(q>a)return}this.children[f].fuzzyRecurse(g,
a,b,c,o,e,h+f)}.bind(this))};return f}();n=function(){function f(a,b,c,d,e){this.avgLengths=a;this.documents=b;this.searchIndex=c;this.weights=d||a.map(function(){return 1});this.bm25Params=e||{};this.bm25Params.k=this.bm25Params.k||1.2;this.bm25Params.b=this.bm25Params.b||0.7;this.bm25Params.d=this.bm25Params.d||0.5}function g(a,b){Object.keys(b).forEach(function(c){a[c]=a[c]||0;a[c]+=b[c]});return a}f.normalizeWord=function(a){return a.toLowerCase().replace(/[^a-z0-9]+/g,"")};f.isStopword=function(a){var b=
"all,and,are,but,can,for,from,has,have,his,may,more,not,one,that,the,then,there,they,this,two,was,when,which,who,will,with,would,you".split(",");return a.length<=2||b.indexOf(a)>-1};f.fromJSON=function(a,b,c){return new f(a[0],a[1],i.fromJSON(a[2]),b,c)};f.getScore=function(a,b){return Math.log((a.totalCount-a.matchCount+0.5)/(a.matchCount+0.5)+1)*(b.d+a.freq*(b.k+1)/(a.freq+b.k*(1-b.b+b.b*a.fieldLength/a.avgFieldLength)))};f.combineOr=function(a,b){var c=a.slice(),d,e;d=0;a:for(;d<b.length;d++){for(e=
0;e<a.length;e++)if(a[e].doc===b[d].doc){c[e].score+=b[d].score;g(c[e].terms,b[d].terms);continue a}c.push(b[d])}return c};f.combineAnd=function(a,b){var c=[],d,e;d=0;a:for(;d<a.length;d++)for(e=0;e<b.length;e++)if(a[d].doc===b[e].doc){c.push({doc:a[d].doc,score:a[d].score+b[e].score,terms:g(a[d].terms,b[e].terms)});continue a}return c};f.combineNot=function(a,b){var c=[],d,e;d=0;a:for(;d<a.length;d++){for(e=0;e<b.length;e++)if(a[d].doc===b[e].doc)continue a;c.push(a[d])}return c};f.prototype.resultsToScore=
function(a,b){return a.map(function(c){var d=0,e,g={};for(e=1;e<c.length;e++)c[e]&&(d+=f.getScore({totalCount:this.documents.length,matchCount:a.length,freq:c[e],fieldLength:this.documents[c[0]][e],avgFieldLength:this.avgLengths[e-1]},this.bm25Params)*this.weights[e-1]);g[b]=d;return{doc:c[0],score:d,terms:g}}.bind(this))};f.prototype.limitToFieldIndex=function(a,b){return a.map(function(a){return a[b]?a.map(function(a,c){return c===0||c===b?a:0}):null}).filter(function(a){return a})};f.prototype.findTerm=
function(a,b){var c=this.searchIndex.get(a)||[];b&&(c=this.limitToFieldIndex(c,b));return this.resultsToScore(c,a)};f.prototype.findTermPrefix=function(a,b,c){var d=[],e=a.length;c&&(e+=c.length);this.searchIndex.forEachPrefix(a,function(a,f){if(!c||!(a.length<e)&&a.endsWith(c))b&&(f=this.limitToFieldIndex(f,b)),this.resultsToScore(f,a).forEach(function(b){var c;b.score*=a.length/(a.length+0.3*(a.length-e));for(c=0;c<d.length;c++)if(d[c].doc===b.doc){d[c].score+=b.score;d[c].terms[a]=d[c].terms[a]||
0;d[c].terms[a]+=b.score;return}d.push(b)})}.bind(this));return d};f.prototype.findTermFuzzy=function(a,b,c,d){var e=[];this.searchIndex.findFuzzy(a,Math.min(Math.floor(c*a.length),d)).forEach(function(a){var c=a[0],d=a[1];b&&(d=this.limitToFieldIndex(d,b));this.resultsToScore(d,c).forEach(function(b){var d;b.score*=c.length/(c.length+a[2]);for(d=0;d<e.length;d++)if(e[d].doc===b.doc){e[d].score+=b.score;e[d].terms[c]=e[d].terms[c]||0;e[d].terms[c]+=b.score;return}e.push(b)})}.bind(this));return e};
f.prototype.execSimpleQuery=function(a){return a.prefix?this.findTermPrefix(a.term,a.fieldIndex,a.suffix):a.fuzzy?this.findTermFuzzy(a.term,a.fieldIndex,a.fuzzy[0],a.fuzzy[1]):this.findTerm(a.term,a.fieldIndex)};f.prototype.execComplexQuery=function(a){return a.term?this.execSimpleQuery(a):a.subqueries.map(this.execComplexQuery.bind(this)).reduce(function(b,c,d){switch(a.combine[d-1]){case "AND":return f.combineAnd(b,c);case "OR":return f.combineOr(b,c);case "NOT":return f.combineNot(b,c)}})};f.prototype.parseSimpleQuery=
function(a,b,c){var d,e,g;e=a.indexOf("*");a.charAt(0)==='"'&&a.charAt(a.length-1)==='"'?(d="exact",a=a.slice(1,-1)):a.charAt(a.length-1)==="~"?(d="fuzzy",a=a.slice(0,-1)):e>-1&&e===a.lastIndexOf("*")?(d="prefix",g=f.normalizeWord(a.slice(e+1)),a=a.slice(0,e)):d=b.fuzzy?"fuzzy":b.prefix?"prefix":"exact";a=f.normalizeWord(a);return d==="exact"&&f.isStopword(a)?null:!a?null:{term:a,fieldIndex:c||b.fieldIndex,prefix:d==="prefix",suffix:g,fuzzy:d==="fuzzy"?[0.3,3]:!1}};f.prototype.parseComplexQuery=function(a,
b,c){function d(a){var b;a:{var c,e,f;b=a.indexOf("(");if(b===-1)b=[-1,-1];else{c=a.indexOf("(",b+1);e=a.indexOf(")",b+1);for(f=1;;){if(e===-1){b=[b,-1];break a}if(c!==-1&&c<e)f++,c=a.indexOf("(",c+1);else{if(f===1){b=[b,e];break a}f--;e=a.indexOf(")",e+1)}}b=void 0}}if(b[0]===-1)return a.split(/\s+/);c=a.slice(0,b[0]).split(/\s+/);b[1]===-1?c.push(a.slice(b[0])+")"):(c.push(a.slice(b[0],b[1]+1)),c=c.concat(d(a.slice(b[1]+1))));return c}var e,f,g={subqueries:[],combine:[]};d(a).forEach(function(a){var d,
j;if(["AND","OR","NOT"].indexOf(a)>-1)e=a;else if(a.charAt(0)==="-"&&(e="NOT",a=a.slice(1)),b.fields&&(d=a.indexOf(":"),d>-1&&(j=a.slice(0,d),b.fields[j]&&(f=b.fields[j],a=a.slice(d+1)))),a){if(a=a.charAt(0)==="("&&a.charAt(a.length-1)===")"?this.parseComplexQuery(a.slice(1,-1),b,f||c):this.parseSimpleQuery(a,b,f||c))g.subqueries.length&&g.combine.push(e||b.combine||"AND"),g.subqueries.push(a);e="";f=0}}.bind(this));return g.subqueries.length?g:null};f.prototype.search=function(a,b){var c,a=this.parseComplexQuery(a,
b||{});if(!a)return[];c=this.execComplexQuery(a);c.sort(function(a,b){return b.score-a.score});return c.map(function(a){var b=Object.keys(a.terms);b.sort(function(b,c){return a.terms[c]-a.terms[b]});return{data:this.documents[a.doc][0],score:a.score,terms:b}}.bind(this))};f.prototype.suggest=function(a,b){var c=[],d=a.lastIndexOf(" "),e=f.normalizeWord(a.slice(d+1));if(e.length<=(b||2))return[];this.searchIndex.forEachPrefix(e,function(b,d){c.push([a+b.slice(e.length),d.length])});c.sort(function(a,
b){return b[1]-a[1]});return c.map(function(a){return a[0]})};return f}();(function(){function f(a){return a.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function g(a){return a.map(function(a){var b=a.data[0],c=a.data[1];b.indexOf("preface.html")>-1&&(c+=" (Preface)");return'<li><a href="../'+b+'">'+c+"</a> <small>(Score: "+Math.round(5*a.score)+"; "+f(a.terms.join(", "))+")</small></li>"}).join("")}function a(a){var b=document.getElementById("search-input").value;
a&&(a.preventDefault(),history.pushState({},"","?q="+encodeURIComponent(b)));document.title="Search: "+b;a=l.search(b,{combine:document.getElementById("option-or").checked?"OR":"AND",prefix:document.getElementById("option-prefix").checked,fuzzy:document.getElementById("option-fuzzy").checked,fieldIndex:document.getElementById("option-title").checked?2:void 0,fields:{text:1,content:1,title:2}});switch(a.length){case 0:b="No results";break;case 1:b="<b>1</b> result";break;default:b="<b>"+a.length+"</b> results"}document.getElementById("result-count").innerHTML=
b;document.getElementById("results").innerHTML=g(a)}function b(){h&&clearTimeout(h);h=setTimeout(c,50)}function c(){var a=document.getElementById("search-input").value,a=l.suggest(a);if(a.length>5)a.length=5;a=a.map(function(a){return'<option value="'+f(a+" ")+'"></option>'});document.getElementById("suggestions").innerHTML=a.join("")}function d(a){var b=location.search.slice(1).split("&").filter(function(b){return b.startsWith(a+"=")});if(!b.length)return"";b=b[b.length-1].slice(a.length+1);try{b=
decodeURIComponent(b)}catch(c){}return b}function e(){var b=d("q"),c;c=document.getElementById("search-input");(c.value=b)?l?a():i=!0:(document.title="Search",document.getElementById("result-count").innerHTML="",document.getElementById("results").innerHTML="",c.focus())}var h,l,i;window.addEventListener("popstate",e,!1);e();(function(a,b){var c=new XMLHttpRequest;c.open("GET",a);c.responseType="text";c.onload=function(){b(n.fromJSON(JSON.parse(c.response),[1,1.5]))};c.send()})("../search-index.json",
function(c){l=c;document.getElementById("search-form").addEventListener("submit",a,!1);document.getElementById("search-input").addEventListener("input",b,!1);i&&a()})})()})();
